# Generated by Django 3.1.2 on 2020-11-12 02:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20201101_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1, "You can't  have an empty list item")]),
        ),
    ]
