# Generated by Django 3.1.2 on 2020-11-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_auto_20201112_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
