# Generated by Django 3.1.2 on 2020-11-12 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_auto_20201112_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='list',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1, message="You can't  have an empty list item")]),
        ),
    ]
