# Generated by Django 3.1.2 on 2020-11-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0011_auto_20201112_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='text',
            field=models.TextField(),
        ),
    ]
